export const MSG_ADD_TO_CART_SUCCCESS = "Mua hàng thành công"
export const MSG_UPDATE_TO_CART_SUCCCESS = "Cập nhật giỏ hàng thành công"
export const MSG_DELETE_TO_CART_SUCCCESS = "Xóa sản phẩm khỏi giỏ hàng thành công"
export const MSG_CART_EMPTY = "Chưa có sản phẩm nào trong giỏ hàng"
export const MSG_WELLCOME = "Chào mừng bạn đến với trang web mua hàng shopping online"